### ISSUE TITLE
option to send messages to a room, but exclude self as a recipient ? 

### ISSUE THREAD

**Issue by looshi** [YuukanOO/streamy-rooms#1]
Is it possible to not send messages back to the user who created them ?  

Steps to replicate : 
1 - User A and User B join the room
Streamy.join('room', userID);

2 - User A and User B both listen for the 'connected' message
Streamy.on( 'connected', function(data, from){
  // do something
});
3 - User A sends message : 
Streamy.rooms('room').emit('connected', data);

desired results : 
User B recieves the 'connected' message.
User A does not receive the 'connected' message 

actual results : 
User A and User B both receive the 'connected' message.

Notes
I can ignore incoming message handlers in the client by checking who sent.  However, I'm having to do this per message handler so it adds a lot of code to the client portion of my app.  Wondering if there is some option or server side way to do this ?  thanks.

**Comment by YuukanOO** [comment]
I'll add a server side callback before the session emit. This way, you'll just have to define it to do nothing if `sid == sender_id`.

**Comment by looshi** [comment]
@YuukanOO that would be awesome, thanks! 
Actually after opening this ticket I realized it's not trivial to ignore self-created messages on the client, so this would be a really great feature addition for my use-case.

**Comment by YuukanOO** [comment]
Closed with eda47f7fb7b6f3bbf39f78d543a3364cad37fac9
